# Generated by Django 3.1.2 on 2020-10-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restauracja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=50)),
                ('ulica', models.CharField(max_length=50)),
                ('nr_budynku', models.IntegerField()),
                ('nr_mieszkania', models.IntegerField()),
                ('restauracja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzenie.restauracja')),
            ],
        ),
    ]
