# Generated by Django 3.1.2 on 2020-10-26 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jedzenie', '0003_auto_20201026_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wlasciciel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpiniaORestauracji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('zadowolenie_klienta', models.IntegerField()),
                ('restauracja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jedzenie.restauracja')),
            ],
        ),
        migrations.AddField(
            model_name='restauracja',
            name='wlasciciel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jedzenie.wlasciciel'),
        ),
    ]
