# Generated by Django 3.1.1 on 2020-12-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0004_auto_20201026_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauracja',
            name='nazwa',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
