# Generated by Django 3.1.1 on 2020-12-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0005_restauracja_nazwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauracja',
            name='zdjecie',
            field=models.ImageField(default=False, upload_to='restauracje', verbose_name='Image'),
        ),
    ]
