# Generated by Django 3.1.2 on 2020-12-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0006_restauracja_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pozycja',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='jedzenie.menu'),
        ),
    ]
