# Generated by Django 3.1.2 on 2020-12-27 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0007_auto_20201214_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniaorestauracji',
            name='restauracja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opinie', to='jedzenie.restauracja'),
        ),
    ]
