# Generated by Django 3.1.1 on 2020-12-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0008_auto_20201227_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='typrestauracji',
            name='restauracja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jedzenie.restauracja'),
        ),
    ]
