# Generated by Django 3.1.1 on 2020-12-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0009_typrestauracji_restauracja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typrestauracji',
            name='restauracja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typ_restauracji', to='jedzenie.restauracja'),
        ),
    ]
