# Generated by Django 3.1.1 on 2020-12-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0010_auto_20201230_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typrestauracji',
            name='restauracja',
        ),
    ]
