# Generated by Django 3.1.1 on 2020-12-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0011_remove_typrestauracji_restauracja'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauracja',
            name='typ_restauracji',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jedzenie.typrestauracji'),
        ),
    ]
