# Generated by Django 3.1.1 on 2021-01-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0013_platnosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platnosc',
            name='forma_platnosci',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
