# Generated by Django 3.1.1 on 2021-01-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0015_auto_20210103_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adres',
            name='nr_mieszkania',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
