# Generated by Django 3.1.1 on 2021-01-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0016_auto_20210104_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pozycja',
            old_name='nazwa',
            new_name='nazwadania',
        ),
    ]
