# Generated by Django 3.1.2 on 2021-01-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0017_auto_20210106_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauracja',
            name='adresy',
        ),
        migrations.AddField(
            model_name='restauracja',
            name='adresy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jedzenie.adres'),
        ),
    ]
