# Generated by Django 3.1.1 on 2021-01-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzenie', '0019_auto_20210108_0215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restauracja',
            old_name='nazwadania',
            new_name='nazwa',
        ),
    ]
